// <auto-generated />
namespace LAMS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddEvaluation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEvaluation));
        
        string IMigrationMetadata.Id
        {
            get { return "202112031259107_AddEvaluation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
